# Generated by Django 4.2.30 on 2026-05-23 06:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='书名')),
                ('author', models.CharField(max_length=100, verbose_name='作者')),
                ('isbn', models.CharField(max_length=13, unique=True, verbose_name='ISBN')),
                ('category', models.CharField(default='其他', max_length=50, verbose_name='分类')),
                ('total_quantity', models.IntegerField(default=1, verbose_name='总数量')),
                ('available_quantity', models.IntegerField(default=1, verbose_name='可借数量')),
                ('cover', models.ImageField(blank=True, null=True, upload_to='covers/')),
                ('publish_date', models.DateField(blank=True, null=True, verbose_name='出版日期')),
            ],
        ),
        migrations.CreateModel(
            name='BorrowRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('borrow_date', models.DateField(auto_now_add=True, verbose_name='借书日期')),
                ('due_date', models.DateField(verbose_name='应还日期')),
                ('return_date', models.DateField(blank=True, null=True, verbose_name='实际归还日期')),
                ('status', models.CharField(choices=[('borrowed', '借出'), ('returned', '已还')], default='borrowed', max_length=10, verbose_name='状态')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.book', verbose_name='图书')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='借阅人')),
            ],
            options={
                'ordering': ['-borrow_date'],
            },
        ),
    ]
